#!/bin/bash

set -e

HASH=sha384
FKM_KEY=fkm_privkey.pem
FBM_KEY=fbm_privkey.pem
FKM_PUK=fkm_pubkey.pem
FBM_PUK=fbm_pubkey.pem
PLDFILE=payload.bin
OUTFILE=out.bin


dd if=/dev/urandom of=${PLDFILE} bs=1024 count=1024

echo "*** Generating test keys ..."
openssl genrsa -out ${FKM_KEY} 2048
openssl rsa -in ${FKM_KEY} -outform PEM -pubout -out ${FKM_PUK}
openssl genrsa -out ${FBM_KEY} 2048
openssl rsa -in ${FBM_KEY} -outform PEM -pubout -out ${FBM_PUK}

echo "*** Signing ..."
./SIIPSign.py sign -i ${PLDFILE}:${FBM_KEY} -o ${OUTFILE} -k ${FKM_KEY} -s ${HASH}

echo "*** Verifying with public key ..."
./SIIPSign.py verify -i ${OUTFILE}:${FBM_PUK} -p ${FKM_PUK} -s ${HASH}

echo "*** Decomposing ..."
./SIIPSign.py decompose -i ${OUTFILE}

echo Done!



